#include "render.h"
#include <pthread.h>
#include <semaphore.h>
#include <float.h>

#define NUM_THREADS 12
#define TILE_W 64
#define TILE_H 64
#define COL_GAME_WIDTH (GAME_WIDTH / TILE_W)
#define TILE_COUNT ((GAME_WIDTH / TILE_W) * (GAME_HEIGHT / TILE_H))

#define to_ndc_x(px) ((float)(px) / GAME_WIDTH  * 2.0f - 1.0f)
#define to_ndc_y(py) (1.0f - (float)(py) / GAME_HEIGHT * 2.0f)

// Internal Function Declarations
void set_verline(uint32_t x, uint32_t start, uint32_t end, Color color);
void set_line(V2i v, V2i u, Color color);
void set_triangle(V2i v1, V2i v2, V2i v3, Color color);
void set_triangle_multicolor(V2i v1, V2i v2, V2i v3, Color c1, Color c2, Color c3);
void set_triangle_3d(V3f v1, V3f v2, V3f v3, Color color);
void set_triangle_3d_multicolor(V3f v1, V3f v2, V3f v3, Color c1, Color c2, Color c3);
void set_quad(V2i v1, V2i v2, V2i v3, V2i v4, Color c);
void renderer_draw_triangle(uint32_t tile_x, uint32_t tile_y, Triangle tri);
Color get_color_from_texture(Texture *t, V2f uv);


// TODO there is a need to redo some of this. Because of the nature of the way things are being
// processed via popping off of a stack, rather than it being FIFO, it leads to weird rendering
// issues where for UI the base needs to be pushed on the stack after the text has been rendered.
// It is not ergonomic and is fundamentally wrong in my opinion. It could be fixed by using an
// index that gets reset every frame, and we would zero the arrays out after processing. 
typedef struct {
    int tile_x, tile_y;
    size_t *tri_idx;
} TileBin;

// --- Thread pool ---
typedef struct
{
    pthread_t thread;
    TileBin *bin;
    int active;
} Worker;

TileBin triangle_bins[(GAME_WIDTH / TILE_W) * (GAME_HEIGHT / TILE_H)];
Triangle *triangles = NULL;
Worker workers[NUM_THREADS];
pthread_mutex_t queue_mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t queue_cond = PTHREAD_COND_INITIALIZER;
pthread_cond_t done_cond = PTHREAD_COND_INITIALIZER;

TileBin *work_queue[TILE_COUNT];
int queue_head = 0;
int queue_tail = 0;
int jobs_remaining = 0;
int pool_running = 1;


// TODO The multithread approach was generated by claude. It needs to be revisited.
void *worker_thread(void *arg)
{
    UNUSED(arg);
    while (1)
    {
        pthread_mutex_lock(&queue_mutex);

        while (queue_head == queue_tail && pool_running)
            pthread_cond_wait(&queue_cond, &queue_mutex);

        if (!pool_running && queue_head == queue_tail)
        {
            pthread_mutex_unlock(&queue_mutex);
            return NULL;
        }

        // Grab bin pointer AND increment while still holding the lock
        TileBin *bin = work_queue[queue_head % TILE_COUNT];
        queue_head++;

        // Snapshot the triangle indices we need to process
        // so we can release the lock before doing pixel work
        size_t len = arrlen(bin->tri_idx);

        // TODO this needs to be a fixed buffer of some kind.
        size_t local_idx[len]; // VLA, or heap alloc if len could be huge
        memcpy(local_idx, bin->tri_idx, len * sizeof(size_t));
        arrsetlen(bin->tri_idx, 0); // clear while locked, before workers
                                    // can re-queue this bin next frame

        pthread_mutex_unlock(&queue_mutex);

        for (size_t i = 0; i < len; i++)
        {
            renderer_draw_triangle(
                bin->tile_x * TILE_W,
                bin->tile_y * TILE_H,
                triangles[local_idx[i]] // triangles[] is read-only during dispatch
            );
        }

        pthread_mutex_lock(&queue_mutex);
        jobs_remaining--;
        if (jobs_remaining == 0)
            pthread_cond_signal(&done_cond);
        pthread_mutex_unlock(&queue_mutex);
    }
}

void render_init(void)
{
    renderer.width = GAME_WIDTH;
    renderer.height = GAME_HEIGHT;
    for (size_t i = 0; i < TILE_COUNT; i++)
    {
        int x = i % (GAME_WIDTH / TILE_W);
        int y = i / (GAME_WIDTH / TILE_W);
        triangle_bins[i].tile_x = x;
        triangle_bins[i].tile_y = y;
    }

    for (int i = 0; i < NUM_THREADS; i++)
        pthread_create(&workers[i].thread, NULL, worker_thread, NULL);
}

void render_shutdown(void)
{
    pthread_mutex_lock(&queue_mutex);
    pool_running = 0;
    pthread_cond_broadcast(&queue_cond);
    pthread_mutex_unlock(&queue_mutex);

    for (int i = 0; i < NUM_THREADS; i++)
        pthread_join(workers[i].thread, NULL);
}

void renderer_draw_triangles(void)
{
    // enqueue all non-empty bins
    pthread_mutex_lock(&queue_mutex);
    for (int i = 0; i < TILE_COUNT; i++)
    {
        if (arrlen(triangle_bins[i].tri_idx) > 0)
        {
            work_queue[queue_tail % TILE_COUNT] = &triangle_bins[i];
            queue_tail++;
            jobs_remaining++;
        }
    }
    pthread_cond_broadcast(&queue_cond); // wake all workers

    // wait for all tiles to finish
    while (jobs_remaining > 0)
        pthread_cond_wait(&done_cond, &queue_mutex);
    pthread_mutex_unlock(&queue_mutex);

    // clear triangle list for next frame
    arrsetlen(triangles, 0);
}

Color color_scale(Color c, double value)
{
    return (Color){
        c.r * value,
        c.g * value,
        c.b * value,
        c.a,
    };
}

Color color_add(Color c1, Color c2)
{
    return (Color){
        c1.r + c2.r,
        c1.g + c2.g,
        c1.b + c2.b,
        c1.a + c2.a,
    };
}

Color color_mul(Color c1, Color c2)
{
    return (Color){
        c1.r * c2.r,
        c1.g * c2.g,
        c1.b * c2.b,
        c1.a * c2.a,
    };
}

#define PIXEL_INDEX(x, y) ((size_t)(x) + (size_t)(y) * (size_t)renderer.width)

static inline void set_pixel(int x, int y, Color color)
{
    if (x < 0 || y < 0 || x >= renderer.width || y >= renderer.height)
        return;

    renderer.pixels[PIXEL_INDEX(x, y)] = color.rgba;
}

void set_verline(uint32_t x, uint32_t start, uint32_t end, Color color)
{
    for (uint32_t i = start; i < end; i++)
    {
        set_pixel(x, i, color);
    }
}

void set_line(V2i v, V2i u, Color color)
{
    bool steep = false;
    if (abs(v.x - v.y) < abs(u.x - u.y))
    {
        V2i temp;
        temp = v;
        v = u;
        u = temp;
        steep = true;
    }

    int y = v.y;
    int ierror = 0;
    for (int x = v.x; x < u.x; x++)
    {
        if (steep)
            set_pixel(y, x, color);
        else
            set_pixel(x, y, color);
        ierror += abs(u.y - v.y);
        if (ierror > u.x - v.x)
        {
            y += u.y > v.y ? 1 : -1;
            ierror -= 2 * (u.x - v.x);
        }
    }
}

bool check_bounds(V2i v1, V2i v2, V2i v3)
{
    if (v1.x < 0 || v1.x > GAME_WIDTH || v2.x < 0 || v2.x > GAME_WIDTH || v3.x < 0 || v3.x > GAME_WIDTH || v1.y < 0 || v1.y > GAME_HEIGHT || v2.y < 0 || v2.y > GAME_HEIGHT || v3.y < 0 || v3.y > GAME_HEIGHT)
        return false;

    return true;
}

void set_triangle(V2i v1, V2i v2, V2i v3, Color color)
{
    AABBi rec = {
        v2i(min(v1.x, min(v2.x, v3.x)), min(v1.y, min(v2.y, v3.y))),
        v2i(max(v1.x, max(v2.x, v3.x)), max(v1.y, max(v2.y, v3.y))),
    };
    V3f bary;

    for (int x = rec.min.x; x < rec.max.x; x++)
    {
        for (int y = rec.min.y; y < rec.max.y; y++)
        {
            if (barycentric(v1, v2, v3, v2i(x, y), &bary))
            {
                set_pixel((uint32_t)x, (uint32_t)y, color);
            }
        }
    }
}

void set_triangle_multicolor(V2i v1, V2i v2, V2i v3, Color c1, Color c2, Color c3)
{
    AABBi rec = {
        v2i(min(v1.x, min(v2.x, v3.x)), min(v1.y, min(v2.y, v3.y))),
        v2i(max(v1.x, max(v2.x, v3.x)), max(v1.y, max(v2.y, v3.y))),
    };
    V3f bary;

    for (int x = rec.min.x; x < rec.max.x; x++)
    {
        for (int y = rec.min.y; y < rec.max.y; y++)
        {
            if (barycentric(v1, v2, v3, v2i(x, y), &bary))
            {
                Color color = color_add(color_add(color_scale(c1, bary.x), color_scale(c2, bary.y)), color_scale(c3, bary.z));
                set_pixel((uint32_t)x, (uint32_t)y, color);
            }
        }
    }
}

void renderer_push_triangle(V3f v1, V3f v2, V3f v3, Color color[3], V3f uvs[3], Texture *t)
{
    V2i pos1 = to_screen(project(v1));
    V2i pos2 = to_screen(project(v2));
    V2i pos3 = to_screen(project(v3));
    if (!check_bounds(pos1, pos2, pos3))
        return;

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };

    size_t t_minx = max(0, floor(rec.min.x / TILE_W));
    size_t t_maxx = min((GAME_WIDTH / TILE_W) - 1, floor(rec.max.x / TILE_W));
    size_t t_miny = max(0, floor(rec.min.y / TILE_H));
    size_t t_maxy = min((GAME_HEIGHT / TILE_H) - 1, floor(rec.max.y / TILE_H));

    if (t_minx > t_maxx || t_miny > t_maxy)
        return;

    Triangle triangle = {
        .vertices = {v1, v2, v3},
        .colors = {color[0], color[1], color[2]},
        .uvs = {uvs[0], uvs[1], uvs[2]},
        .texture = t,
    };
    arrput(triangles, triangle);
    size_t idx = arrlen(triangles) - 1;

    for (size_t j = t_miny; j <= t_maxy; j++)
    {
        for (size_t i = t_minx; i <= t_maxx; i++)
        {
            arrput(triangle_bins[i + j * COL_GAME_WIDTH].tri_idx, idx);
        }
    }
}

void renderer_push_triangle_w_normals(V3f positions[3], V3f normals[3], Color color[3])
{
    V2i pos1 = to_screen(project(positions[0]));
    V2i pos2 = to_screen(project(positions[1]));
    V2i pos3 = to_screen(project(positions[2]));
    if (!check_bounds(pos1, pos2, pos3))
        return;

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };

    size_t t_minx = max(0, floor(rec.min.x / TILE_W));
    size_t t_maxx = min((GAME_WIDTH / TILE_W) - 1, floor(rec.max.x / TILE_W));
    size_t t_miny = max(0, floor(rec.min.y / TILE_H));
    size_t t_maxy = min((GAME_HEIGHT / TILE_H) - 1, floor(rec.max.y / TILE_H));

    if (t_minx > t_maxx || t_miny > t_maxy)
        return;

    Triangle triangle = {
        .vertices = {positions[0], positions[1], positions[2]},
        .normals = {normals[0], normals[1], normals[2]},
        .colors = {color[0], color[1], color[2]},
        .texture = NULL,
    };
    arrput(triangles, triangle);
    size_t idx = arrlen(triangles) - 1;

    for (size_t j = t_miny; j <= t_maxy; j++)
    {
        for (size_t i = t_minx; i <= t_maxx; i++)
        {
            arrput(triangle_bins[i + j * COL_GAME_WIDTH].tri_idx, idx);
        }
    }
}

Color color_modulate(Color a, Color b)
{
    return (Color){
        (uint8_t)(a.r * b.r / 255),
        (uint8_t)(a.g * b.g / 255),
        (uint8_t)(a.b * b.b / 255),
        (uint8_t)(a.a * b.a / 255),
    };
}

void renderer_draw_triangle(uint32_t tile_x, uint32_t tile_y, Triangle tri)
{
    V2i pos1 = to_screen(project(tri.vertices[0]));
    V2i pos2 = to_screen(project(tri.vertices[1]));
    V2i pos3 = to_screen(project(tri.vertices[2]));

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };

    int x0 = max(rec.min.x, (int)tile_x);
    int x1 = min(rec.max.x, (int)(tile_x + TILE_W));
    int y0 = max(rec.min.y, (int)tile_y);
    int y1 = min(rec.max.y, (int)(tile_y + TILE_H));

    V3f bary;

    double total_area = signed_area(pos1.x, pos1.y, pos2.x, pos2.y, pos3.x, pos3.y);
    if (total_area < -1e6)
        return;

    for (int y = y0; y < y1; y++)
    {
        for (int x = x0; x < x1; x++)
        {
            if (barycentric(pos1, pos2, pos3, v2i(x, y), &bary))
            {
                double inv_z = (bary.x / tri.vertices[0].z +
                                bary.y / tri.vertices[1].z +
                                bary.z / tri.vertices[2].z);
                double z = 1.0 / inv_z;

                size_t idx = PIXEL_INDEX(x, y);

                if (z >= renderer.zbuffer[idx])
                    continue;

                // TODO Interpolate colors
                Color int_color;
                if (tri.texture != NULL) {
                    V3f v1 = tri.uvs[0];
                    V3f v2 = tri.uvs[1];
                    V3f v3 = tri.uvs[2];
                    float u = v1.x * bary.x + v2.x * bary.y + v3.x * bary.z;
                    float v = v1.y * bary.x + v2.y * bary.y + v3.y * bary.z;

                    Color tex_color = get_color_from_texture(tri.texture, v2f(u, v));

                    Color vert_color = color_add(
                            color_add(
                                color_scale(tri.colors[0], bary.x),
                                color_scale(tri.colors[1], bary.y)),
                            color_scale(tri.colors[2], bary.z));

                    int_color = color_modulate(tex_color, vert_color);
                    if (int_color.rgba == 0) continue;
                } else {
                    int_color = color_add(
                            color_add(
                                color_scale(tri.colors[0], bary.x),
                                color_scale(tri.colors[1], bary.y)),
                            color_scale(tri.colors[2], bary.z));
                }

                renderer.zbuffer[idx] = z;
                set_pixel((uint32_t)x, (uint32_t)y, int_color); //  (Color){c, c, c, 255});
            }
        }
    }
}

void draw_point(V3f p, Color color)
{
    V2i pos = to_screen(project(p));

    set_pixel(pos.x, pos.y, color);
}

void set_triangle_3d(V3f v1, V3f v2, V3f v3, Color color)
{
    V2i pos1 = to_screen(project(v1));
    V2i pos2 = to_screen(project(v2));
    V2i pos3 = to_screen(project(v3));

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };
    V3f bary;

    double total_area = signed_area(pos1.x, pos1.y, pos2.x, pos2.y, pos3.x, pos3.y);
    if (total_area < -1e6)
        return;

    for (int y = rec.min.y; y < rec.max.y; y++)
    {
        for (int x = rec.min.x; x < rec.max.x; x++)
        {
            if (barycentric(pos1, pos2, pos3, v2i(x, y), &bary))
            {
                double z = (bary.x * v1.z + bary.y * v2.z + bary.z * v3.z);
                // logger(LOG_DEBUG, "z: %c, zbuf: %f", z, renderer.zbuffer[y][x]);
                if (z < renderer.zbuffer[x + y * GAME_WIDTH])
                    continue;
                renderer.zbuffer[x + y * GAME_WIDTH] = z;

                set_pixel((uint32_t)x, (uint32_t)y, color); // (Color){c, c, c, 255});
            }
        }
    }
}

// Top right, bottom right, top left, bottom left
void set_quad(V2i v1, V2i v2, V2i v3, V2i v4, Color c)
{
    set_triangle(v1, v2, v3, c);
    set_triangle(v1, v3, v4, c);
}

// TODO there is some speed up that could be done here. SIMD
Color get_color_from_texture(Texture *t, V2f uv)
{
    uv.x = fmaxf(0.0f, fminf(1.0f, uv.x));
    uv.y = fmaxf(0.0f, fminf(1.0f, uv.y));

    size_t x = (size_t)(uv.x * (t->width  - 1));
    size_t y = (size_t)(uv.y * (t->height - 1));

    size_t idx = (y * t->width + x) * t->stride;

    Color c;
    c.r = t->data[idx + 0];
    c.g = t->data[idx + 1];
    c.b = t->data[idx + 2];
    // TODO add ability to have clear parts from a texture come through
    c.a = t->stride == 4 ? t->data[idx + 3] : 0;
    return c;
}

void clear_background(Color color)
{
    for (int y = 0; y < renderer.height; y++)
    {
        for (int x = 0; x < renderer.width; x++)
        {
            size_t idx = PIXEL_INDEX(x, y);
            renderer.pixels[idx] = color.rgba;
            renderer.zbuffer[idx] = FLT_MAX;
        }
    }
}

void draw_model(Asset_Model *model, V3f position, Mat3 rotation)
{
    V3f light_pos = (V3f){1, 0, 2};

    for (int i = 0; i < arrlen(model->vertices); i += 3)
    {
        Vertex v1 = model->vertices[i];
        Vertex v2 = model->vertices[i + 1];
        Vertex v3 = model->vertices[i + 2];

        V3f p1 = v3f_mul_mat3(v1.position, rotation);
        V3f p2 = v3f_mul_mat3(v2.position, rotation);
        V3f p3 = v3f_mul_mat3(v3.position, rotation);

        p1.z = -p1.z;
        p2.z = -p2.z;
        p3.z = -p3.z;
        p1 = v3f_add(p1, position);
        p2 = v3f_add(p2, position);
        p3 = v3f_add(p3, position);

        if (p1.z <= NEAR || p2.z <= NEAR || p3.z <= NEAR)
            continue;
        light_pos.z += 0.01;
        Color color;
        color.r = (uint8_t)((v1.normal.x * 0.5f + 0.5f) * 255);
        color.g = (uint8_t)((v1.normal.y * 0.5f + 0.5f) * 255);
        color.b = (uint8_t)((v1.normal.z * 0.5f + 0.5f) * 255);
        color.a = 255;
        Color colors[3] = {color};
        V3f uvs[3] = {};

        renderer_push_triangle(
            p1,
            p2,
            p3,
            colors, 
            uvs,
            NULL);
    }
}

void draw_model_with_light(Asset_Model *model, V3f position, Mat3 rotation, Light light)
{
    //Mat4 pers = perspective(NEAR, FAR, ASPECT_RATIO, FOV);
    Mat4 view = camera_matrix(renderer.camera);
    for (int i = 0; i < arrlen(model->vertices); i += 3)
    {
        Vertex v1 = model->vertices[i];
        Vertex v2 = model->vertices[i + 1];
        Vertex v3 = model->vertices[i + 2];

        V3f p1 = v3f_mul_mat3(v1.position, rotation);
        V3f p2 = v3f_mul_mat3(v2.position, rotation);
        V3f p3 = v3f_mul_mat3(v3.position, rotation);

        V3f n1 = v3f_mul_mat3(v1.normal, rotation);
        V3f n2 = v3f_mul_mat3(v2.normal, rotation);
        V3f n3 = v3f_mul_mat3(v3.normal, rotation);

        p1.z = -p1.z;
        p2.z = -p2.z;
        p3.z = -p3.z;
        p1 = v3f_add(p1, position);
        p2 = v3f_add(p2, position);
        p3 = v3f_add(p3, position);

        p1 = v3f_translate_by_mat4(p1, view);
        p2 = v3f_translate_by_mat4(p2, view);
        p3 = v3f_translate_by_mat4(p3, view);

        if (p1.z <= NEAR || p2.z <= NEAR || p3.z <= NEAR)
            continue;
        Color t1;
        Color t2;
        Color t3;
        t1 = COLOR_WHITE;
        t2 = COLOR_WHITE;
        t3 = COLOR_WHITE;

        Color c1 = simple_reflection(model->mtl, light.position, p1, n1, light.color, t1);
        Color c2 = simple_reflection(model->mtl, light.position, p2, n2, light.color, t2);
        Color c3 = simple_reflection(model->mtl, light.position, p3, n3, light.color, t3);

        Color colors[3] = {c1, c2, c3};
        V3f uvs[3] = {v1.uv, v2.uv, v3.uv};
        renderer_push_triangle(
            p1,
            p2,
            p3,
            colors,
            uvs,
            model->mtl->diffuse_texture);
    }
}

Color simple_reflection(SimpleMtl *mtl, V3f light_pos, V3f v, V3f n, V3f light_color, Color object_color)
{
    if (mtl == NULL)
        return object_color;
    V3f norm = v3f_normalize(n);
    V3f light_dir = v3f_normalize(v3f_sub(light_pos, v));

    float diff = fmaxf(v3f_dot(norm, light_dir), 0.0f);

    V3f obj = {
        object_color.r / 255.0,
        object_color.g / 255.0,
        object_color.b / 255.0,
    };
    V3f diffuse = v3f_scale(light_color, diff);
    V3f result = v3f_mul(v3f_add(diffuse, mtl->ambient), obj);

    Color res = (Color){
        .r = (uint8_t)(fminf(result.x, 1.0f) * 255),
        .g = (uint8_t)(fminf(result.y, 1.0f) * 255),
        .b = (uint8_t)(fminf(result.z, 1.0f) * 255),
        .a = 255,
    };
    return res;
}

void draw_texture(Texture *tex, Reci rec)
{
    float x0 = to_ndc_x(rec.x);
    float y0 = to_ndc_y(rec.y);
    float x1 = to_ndc_x(rec.x + rec.w);
    float y1 = to_ndc_y(rec.y + rec.h);

    // Tri 1: TL, BR, BL
    V3f uvs1[3] = {
        {1.0f, 1.0f, 1.0f},  // BR
        {1.0f, 0.0f, 1.0f},  // TR
        {0.0f, 0.0f, 1.0f},  // TL
    };
    // Tri 2: TL, TR, BR
    V3f uvs2[3] = {
        {0.0f, 1.0f, 1.0f},  // BL
        {1.0f, 1.0f, 1.0f},  // BR
        {0.0f, 0.0f, 1.0f},  // TL
    };

    Color colors[3] = {};

    renderer_push_triangle(
            v3f(x1, y1, 1),   // BR
            v3f(x1, y0, 1),   // TR
            v3f(x0, y0, 1),   // TL
        colors, uvs1, tex);

    renderer_push_triangle(
            v3f(x0, y1, 1),   // BL
            v3f(x1, y1, 1),   // BR
            v3f(x0, y0, 1),   // TL
        colors, uvs2, tex);
}

void draw_texture_w_uvs(Texture *tex, Reci rec, V3f uvs[4], Color colors[4])
{
    float x0 = to_ndc_x(rec.x);
    float y0 = to_ndc_y(rec.y);
    float x1 = to_ndc_x(rec.x + rec.w);
    float y1 = to_ndc_y(rec.y + rec.h);

    // Tri 1: TL, BR, BL
    V3f uvs1[3] = {
        uvs[2],
        uvs[1],
        uvs[0]
    };

    // Tri 2: TL, TR, BR
    V3f uvs2[3] = {
        uvs[3],
        uvs[2],
        uvs[0]
    };

    Color c1[3] = {
        colors[2],
        colors[1],
        colors[0],
    };

    Color c2[3] = {
        colors[3],
        colors[2],
        colors[0],
    };

    renderer_push_triangle(
            v3f(x1, y1, 1),   // BR
            v3f(x1, y0, 1),   // TR
            v3f(x0, y0, 1),   // TL
        c1, uvs1, tex);

    renderer_push_triangle(
            v3f(x0, y1, 1),   // BL
            v3f(x1, y1, 1),   // BR
            v3f(x0, y0, 1),   // TL
        c2, uvs2, tex);
}

void draw_reci(Reci rec, float z, Color color)
{
    float x0 = to_ndc_x(rec.x);
    float y0 = to_ndc_y(rec.y);
    float x1 = to_ndc_x(rec.x + rec.w);
    float y1 = to_ndc_y(rec.y + rec.h);

    V3f uvs[3] = {};
    Color colors[3] = {color, color, color};

    renderer_push_triangle(
            v3f(x1, y1, z),   // BR
            v3f(x1, y0, z),   // TR
            v3f(x0, y0, z),   // TL
        colors, uvs, NULL);

    renderer_push_triangle(
            v3f(x0, y1, z),   // BL
            v3f(x1, y1, z),   // BR
            v3f(x0, y0, z),   // TL
        colors, uvs, NULL);
}

// TODO AI GENERATED. REVISIT FOR FIXES

#define GLYPH_W   8
#define GLYPH_H   16

void draw_text(Font *f, const char *str, V2i pos, float size, Color color)
{
    int atlas_w = f->texture->width;
    int atlas_h = f->texture->height;
    int sprites_per_row = atlas_w / GLYPH_W;

    char c = str[0];
    int i = 0;
    while (c != '\0') {
        int tex_id = (unsigned char)c;
        int col    = tex_id % sprites_per_row;
        int row    = tex_id / sprites_per_row;

        float u_min = (float)(col * GLYPH_W)          / (float)atlas_w;
        float v_min = (float)(row * GLYPH_H)          / (float)atlas_h;
        float u_max = (float)(col * GLYPH_W + GLYPH_W) / (float)atlas_w;
        float v_max = (float)(row * GLYPH_H + GLYPH_H) / (float)atlas_h;

        V3f uvs[4] = {
            v3f(u_min, v_min, 0),  /* top-left     */
            v3f(u_max, v_min, 0),  /* top-right    */
            v3f(u_max, v_max, 0),  /* bottom-right */
            v3f(u_min, v_max, 0),  /* bottom-left  */
        };
        Color colors[4] = {color, color, color, color};
        draw_texture_w_uvs(
            f->texture,
            (Reci){ .x = pos.x + (i * (int)size), .y = pos.y,
                    .w = (int)size, .h = (int)size },
            uvs,
            colors);

        i++;
        c = str[i];
    }
}
