/*
 * This is the Software Rasterizer backend. There is a plan to add either an OpenGL or Vulkan backend in the 
 * future. However, for the meantime, this is more than fast enough on my macbook to do testing and development.
 *
 */
#include "render.h"

#define NUM_THREADS 14
#define TILE_W 64
#define TILE_H 64
#define COL_GAME_WIDTH (GAME_WIDTH / TILE_W)
#define TILE_COUNT ((GAME_WIDTH / TILE_W) * (GAME_HEIGHT / TILE_H))

typedef struct {
    u32 len;
    u32 capacity;
    Triangle *data;
} TriangleArray;

typedef struct {
    u32 len;
    u32 capacity;
    size_t *data;
} SizeArray;

#define array_push(a, v)                                        \
    do {                                                        \
        if (((a)->len + 1 < (a)->capacity)) {               \
            (a)->data[(a)->len] = v;                            \
            (a)->len += 1;                                      \
        } else {                                                \
            u32 new_cap = (a)->capacity ? ((a)->capacity * 2) : 2;\
            (a)->data = realloc((a)->data, new_cap * sizeof(v));\
            (a)->capacity = new_cap;                            \
            (a)->data[(a)->len] = v;                            \
            (a)->len++;                                         \
        }                                                       \
    } while (0);

#define to_ndc_x(px) ((f32)(px) / GAME_WIDTH * 2.0f - 1.0f)
#define to_ndc_y(py) (1.0f - (f32)(py) / GAME_HEIGHT * 2.0f)

// Internal Function Declarations
void set_verline(u32 x, u32 start, u32 end, Color color);
void set_line(V2i v, V2i u, Color color);
void set_triangle(V2i v1, V2i v2, V2i v3, Color color);
void set_triangle_multicolor(V2i v1, V2i v2, V2i v3, Color c1, Color c2, Color c3);
void set_triangle_3d(V3f v1, V3f v2, V3f v3, Color color);
void set_triangle_3d_multicolor(V3f v1, V3f v2, V3f v3, Color c1, Color c2, Color c3);
void set_quad(V2i v1, V2i v2, V2i v3, V2i v4, Color c);
void renderer_draw_triangle(u32 tile_x, u32 tile_y, Triangle tri);
Color get_color_from_texture(Texture *t, V2f uv);

typedef struct {
    s32 tile_x, tile_y;
    SizeArray tri_idx;
} TileBin;

typedef struct
{
    pthread_t thread;
    TileBin *bin;
    s32 active;
} Worker;

TileBin triangle_bins[(GAME_WIDTH / TILE_W) * (GAME_HEIGHT / TILE_H)];
TriangleArray *triangles;
Worker workers[NUM_THREADS];
pthread_mutex_t queue_mutex = PTHREAD_MUTEX_INITIALIZER;
pthread_cond_t queue_cond = PTHREAD_COND_INITIALIZER;
pthread_cond_t done_cond = PTHREAD_COND_INITIALIZER;

TileBin *work_queue[TILE_COUNT];
s32 queue_head = 0;
s32 queue_tail = 0;
s32 jobs_remaining = 0;
s32 pool_running = 1;

// TODO The multithread approach was generated by claude. It needs to be revisited.
void *worker_thread(void *arg)
{
    UNUSED(arg);
    while (1)
    {
        pthread_mutex_lock(&queue_mutex);

        while (queue_head == queue_tail && pool_running)
            pthread_cond_wait(&queue_cond, &queue_mutex);

        if (!pool_running && queue_head == queue_tail)
        {
            pthread_mutex_unlock(&queue_mutex);
            return NULL;
        }

        // Grab bin pos32er AND increment while still holding the lock
        TileBin *bin = work_queue[queue_head % TILE_COUNT];
        queue_head++;

        // Snapshot the triangle indices we need to process
        // so we can release the lock before doing pixel work
        size_t len = bin->tri_idx.len;

        // TODO this needs to be a fixed buffer of some kind.
        size_t local_idx[len]; // VLA, or heap alloc if len could be huge
        memcpy(local_idx, bin->tri_idx.data, len * sizeof(size_t));
        bin->tri_idx.len = 0; // clear while locked, before workers
                                    // can re-queue this bin next frame

        pthread_mutex_unlock(&queue_mutex);

        for (size_t i = 0; i < len; i++)
        {
            renderer_draw_triangle(
                bin->tile_x * TILE_W,
                bin->tile_y * TILE_H,
                triangles->data[local_idx[i]] // triangles[] is read-only during dispatch
            );
        }

        pthread_mutex_lock(&queue_mutex);
        jobs_remaining--;
        if (jobs_remaining == 0)
            pthread_cond_signal(&done_cond);
        pthread_mutex_unlock(&queue_mutex);
    }
}

void render_init(void)
{

    triangles = malloc(sizeof(TriangleArray));
    s32 initial = 1000;
    triangles->capacity = initial;
    log_debug("Triangle data pointer %p", triangles->data);
    triangles->data = malloc(sizeof(Triangle) * initial);
    triangles->len = 0;
    log_debug("Triangle data pointer %p", triangles->data);
    renderer.width = GAME_WIDTH;
    renderer.height = GAME_HEIGHT;
    for (size_t i = 0; i < TILE_COUNT; i++)
    {
        s32 x = i % (GAME_WIDTH / TILE_W);
        s32 y = i / (GAME_WIDTH / TILE_W);
        triangle_bins[i].tile_x = x;
        triangle_bins[i].tile_y = y;
        triangle_bins[i].tri_idx.data = malloc(initial * sizeof(size_t));
        triangle_bins[i].tri_idx.capacity = initial;
    }

    for (s32 i = 0; i < NUM_THREADS; i++)
        pthread_create(&workers[i].thread, NULL, worker_thread, NULL);

}

void render_shutdown(void)
{
    pthread_mutex_lock(&queue_mutex);
    pool_running = 0;
    pthread_cond_broadcast(&queue_cond);
    pthread_mutex_unlock(&queue_mutex);

    for (s32 i = 0; i < NUM_THREADS; i++)
        pthread_join(workers[i].thread, NULL);
}


void change_camera(void)
{
    Camera temp_camera;
    temp_camera = renderer.swap_camera;
    renderer.swap_camera = renderer.camera;
    renderer.camera = temp_camera;
}

void renderer_flush(void)
{
    //log_info("Triangles rendererd %zd", triangles->len);
    // enqueue all non-empty bins
    pthread_mutex_lock(&queue_mutex);
    for (s32 i = 0; i < TILE_COUNT; i++)
    {
        if (triangle_bins[i].tri_idx.len > 0)
        {
            work_queue[queue_tail % TILE_COUNT] = &triangle_bins[i];
            queue_tail++;
            jobs_remaining++;
        }
    }
    pthread_cond_broadcast(&queue_cond); // wake all workers

    // wait for all tiles to finish
    while (jobs_remaining > 0)
        pthread_cond_wait(&done_cond, &queue_mutex);
    pthread_mutex_unlock(&queue_mutex);

    // clear triangle list for next frame
    triangles->len = 0;
}


#define PIXEL_INDEX(x, y) ((size_t)(x) + (size_t)(y) * (size_t)renderer.width)

static inline void set_pixel(s32 x, s32 y, Color src)
{
    if (x < 0 || y < 0 || x >= renderer.width || y >= renderer.height)
        return;

    size_t idx = PIXEL_INDEX(x, y);
    Color dst = (Color)renderer.pixels[idx];

    if (src.a == 0)
        return;

    if (src.a == 255) {
        renderer.pixels[idx] = src.rgba;
        return;
    }

    Color out = alpha_blend(src, dst);
    renderer.pixels[idx] = out.rgba;
}

void set_verline(u32 x, u32 start, u32 end, Color color)
{
    for (u32 i = start; i < end; i++)
    {
        set_pixel(x, i, color);
    }
}

void set_line(V2i v, V2i u, Color color)
{
    bool steep = false;
    if (abs(v.x - v.y) < abs(u.x - u.y))
    {
        V2i temp;
        temp = v;
        v = u;
        u = temp;
        steep = true;
    }

    s32 y = v.y;
    s32 ierror = 0;
    for (s32 x = v.x; x < u.x; x++)
    {
        if (steep)
            set_pixel(y, x, color);
        else
            set_pixel(x, y, color);
        ierror += abs(u.y - v.y);
        if (ierror > u.x - v.x)
        {
            y += u.y > v.y ? 1 : -1;
            ierror -= 2 * (u.x - v.x);
        }
    }
}

bool check_bounds(V2i v1, V2i v2, V2i v3)
{
    if (v1.x < 0 || v1.x > GAME_WIDTH || v2.x < 0 || v2.x > GAME_WIDTH || v3.x < 0 || v3.x > GAME_WIDTH || v1.y < 0 || v1.y > GAME_HEIGHT || v2.y < 0 || v2.y > GAME_HEIGHT || v3.y < 0 || v3.y > GAME_HEIGHT)
        return false;

    return true;
}

void set_triangle(V2i v1, V2i v2, V2i v3, Color color)
{
    AABBi rec = {
        v2i(min(v1.x, min(v2.x, v3.x)), min(v1.y, min(v2.y, v3.y))),
        v2i(max(v1.x, max(v2.x, v3.x)), max(v1.y, max(v2.y, v3.y))),
    };
    V3f bary;

    for (s32 x = rec.min.x; x < rec.max.x; x++)
    {
        for (s32 y = rec.min.y; y < rec.max.y; y++)
        {
            if (barycentric(v1, v2, v3, v2i(x, y), &bary))
            {
                set_pixel((u32)x, (u32)y, color);
            }
        }
    }
}

void set_triangle_multicolor(V2i v1, V2i v2, V2i v3, Color c1, Color c2, Color c3)
{
    AABBi rec = {
        v2i(min(v1.x, min(v2.x, v3.x)), min(v1.y, min(v2.y, v3.y))),
        v2i(max(v1.x, max(v2.x, v3.x)), max(v1.y, max(v2.y, v3.y))),
    };
    V3f bary;

    for (s32 x = rec.min.x; x < rec.max.x; x++)
    {
        for (s32 y = rec.min.y; y < rec.max.y; y++)
        {
            if (barycentric(v1, v2, v3, v2i(x, y), &bary))
            {
                Color color = color_add(color_add(color_scale(c1, bary.x), color_scale(c2, bary.y)), color_scale(c3, bary.z));
                set_pixel((u32)x, (u32)y, color);
            }
        }
    }
}

void renderer_push_triangle(V3f v1, V3f v2, V3f v3, Color color[3], V3f uvs[3], Texture *t, u32 flags)
{
    V2i pos1;
    V2i pos2;
    V2i pos3;
    if (!FlagExists(flags, TRIANGLE_TWO_D))
    {
        pos1 = to_screen(project(v1));
        pos2 = to_screen(project(v2));
        pos3 = to_screen(project(v3));
    }
    else
    {
        pos1 = v2i(v1.x, v1.y);
        pos2 = v2i(v2.x, v2.y);
        pos3 = v2i(v3.x, v3.y);
    }
    /* if (!check_bounds(pos1, pos2, pos3))
        return; */

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };

    size_t t_minx = max(0, floor(rec.min.x / TILE_W));
    size_t t_maxx = min((GAME_WIDTH / TILE_W) - 1, floor(rec.max.x > 0 ? rec.max.x : 0 / TILE_W));
    size_t t_miny = max(0, floor(rec.min.y / TILE_H));
    size_t t_maxy = min((GAME_HEIGHT / TILE_H) - 1, floor(rec.max.y > 0 ? rec.max.y : 0 / TILE_H));

    Triangle triangle = {
        .vertices = {v1, v2, v3},
        .uvs = {uvs[0], uvs[1], uvs[2]},
        .colors = {color[0], color[1], color[2]},
        .texture = t,
        .flags = flags,
    };

    array_push(triangles, triangle);
    size_t idx = triangles->len - 1;

    for (size_t j = t_miny; j <= t_maxy; j++)
    {
        for (size_t i = t_minx; i <= t_maxx; i++)
        {
            size_t index = i + j * COL_GAME_WIDTH;
            if (index < TILE_COUNT)
                array_push(&triangle_bins[index].tri_idx, idx);
        }
    }
}

void renderer_push_triangle_w_normals(V3f positions[3], V3f normals[3], Color color[3], V3f uvs[3], Texture *t, SimpleMtl *material, u32 flags)
{
    V2i pos1;
    V2i pos2;
    V2i pos3;
    if (!FlagExists(flags, TRIANGLE_TWO_D))
    {
        pos1 = to_screen(project(positions[0]));
        pos2 = to_screen(project(positions[1]));
        pos3 = to_screen(project(positions[2]));
    }
    else
    {
        pos1 = v2i(positions[0].x, positions[0].y);
        pos2 = v2i(positions[1].x, positions[1].y);
        pos3 = v2i(positions[2].x, positions[2].y);
    }

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };

    size_t t_minx = max(0, floor(rec.min.x / TILE_W));
    size_t t_maxx = min((GAME_WIDTH / TILE_W) - 1, floor(rec.max.x > 0 ? rec.max.x : 0 / TILE_W));
    size_t t_miny = max(0, floor(rec.min.y / TILE_H));
    size_t t_maxy = min((GAME_HEIGHT / TILE_H) - 1, floor(rec.max.y > 0 ? rec.max.y : 0 / TILE_H));

    Triangle triangle = {
        .vertices = {positions[0], positions[1], positions[2]},
        .normals = {normals[0], normals[1], normals[2]},
        .colors = {color[0], color[1], color[2]},
		.uvs = {uvs[0], uvs[1], uvs[2]},
		.material = material,
        .texture = t,
        .flags = flags,
    };

    array_push(triangles, triangle);
    size_t idx = triangles->len - 1;

    for (size_t j = t_miny; j <= t_maxy; j++)
    {
        for (size_t i = t_minx; i <= t_maxx; i++)
        {
            size_t index = i + j * COL_GAME_WIDTH;
            if (index < TILE_COUNT)
                array_push(&triangle_bins[index].tri_idx, idx);
        }
    }
}

void renderer_draw_triangle(u32 tile_x, u32 tile_y, Triangle tri)
{
    V2i pos1;
    V2i pos2;
    V2i pos3;
	Color c1;
	Color c2;
	Color c3;
    if (FlagExists(tri.flags, TRIANGLE_TWO_D))
    {
        pos1 = v2i((s32)tri.vertices[0].x, (s32)tri.vertices[0].y);
        pos2 = v2i((s32)tri.vertices[1].x, (s32)tri.vertices[1].y);
        pos3 = v2i((s32)tri.vertices[2].x, (s32)tri.vertices[2].y);
		c1 = tri.colors[0];
		c2 = tri.colors[1];
		c3 = tri.colors[2];
    }
    else
    {
        pos1 = to_screen(project(tri.vertices[0]));
        pos2 = to_screen(project(tri.vertices[1]));
        pos3 = to_screen(project(tri.vertices[2]));
		if (tri.material) {

			c1 = simple_reflection(tri.material, renderer.sun.position, tri.vertices[0], tri.normals[0], renderer.sun.color, COLOR_WHITE);
			c2 = simple_reflection(tri.material, renderer.sun.position, tri.vertices[1], tri.normals[1], renderer.sun.color, COLOR_WHITE);
			c3 = simple_reflection(tri.material, renderer.sun.position, tri.vertices[2], tri.normals[2], renderer.sun.color, COLOR_WHITE);
		} else {
			c1 = tri.colors[0];
			c2 = tri.colors[1];
			c3 = tri.colors[2];
		}
    }

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };

    s32 x0 = max(rec.min.x, (s32)tile_x);
    s32 x1 = min(rec.max.x, (s32)(tile_x + TILE_W));
    s32 y0 = max(rec.min.y, (s32)tile_y);
    s32 y1 = min(rec.max.y, (s32)(tile_y + TILE_H));

    V3f bary;

    if (FlagExists(tri.flags, TRIANGLE_NO_CULLING)) {
    } else {
        double total_area = signed_area(pos1.x, pos1.y, pos2.x, pos2.y, pos3.x, pos3.y);
        if (total_area >= 0)
            return;
    }

    for (s32 y = y0; y < y1; y++)
    {
        for (s32 x = x0; x < x1; x++)
        {
            if (barycentric(pos1, pos2, pos3, v2i(x, y), &bary))
            {
                double inv_z = (bary.x / tri.vertices[0].z +
                                bary.y / tri.vertices[1].z +
                                bary.z / tri.vertices[2].z);
                double z = 1.0 / inv_z;

                size_t idx = PIXEL_INDEX(x, y);
                if (idx < 0 || idx > GAME_WIDTH * GAME_HEIGHT) continue;
                if (!FlagExists(tri.flags, TRIANGLE_WRITE_OVER_Z)) {
                    if (z >= renderer.zbuffer[idx])
                        continue;
                }


                // TODO Interpolate colors
                Color s32_color;
                if (tri.texture != NULL)
                {
                    V3f v1 = tri.uvs[0];
                    V3f v2 = tri.uvs[1];
                    V3f v3 = tri.uvs[2];
                    f32 u = (v1.x/tri.vertices[0].z * bary.x +
                            v2.x/tri.vertices[1].z * bary.y +
                            v3.x/tri.vertices[2].z * bary.z) * z;
                    f32 v = (v1.y/tri.vertices[0].z * bary.x +
                            v2.y/tri.vertices[1].z * bary.y +
                            v3.y/tri.vertices[2].z * bary.z) * z;

                    Color tex_color = get_color_from_texture(tri.texture, v2f(u, v));

                    Color vert_color = color_add(
                        color_add(
                            color_scale(c1, bary.x),
                            color_scale(c2, bary.y)),
                        color_scale(c3, bary.z));

                    s32_color = color_modulate(tex_color, vert_color);
                    if (s32_color.a == 0)
                        continue;
                }
                else
                {
                    s32_color = color_add(
                        color_add(
                            color_scale(tri.colors[0], bary.x),
                            color_scale(tri.colors[1], bary.y)),
                        color_scale(tri.colors[2], bary.z));
                }

                renderer.zbuffer[idx] = z;
                set_pixel((u32)x, (u32)y, s32_color); //  (Color){c, c, c, 255});
            }
        }
    }
}

void draw_point(V3f p, Color color)
{
    V2i pos = to_screen(project(p));

    set_pixel(pos.x, pos.y, color);
}

void set_triangle_3d(V3f v1, V3f v2, V3f v3, Color color)
{
    V2i pos1 = to_screen(project(v1));
    V2i pos2 = to_screen(project(v2));
    V2i pos3 = to_screen(project(v3));

    AABBi rec = {
        v2i(min(pos1.x, min(pos2.x, pos3.x)), min(pos1.y, min(pos2.y, pos3.y))),
        v2i(max(pos1.x, max(pos2.x, pos3.x)), max(pos1.y, max(pos2.y, pos3.y))),
    };
    V3f bary;

    double total_area = signed_area(pos1.x, pos1.y, pos2.x, pos2.y, pos3.x, pos3.y);
    if (total_area < -1e6)
        return;

    for (s32 y = rec.min.y; y < rec.max.y; y++)
    {
        for (s32 x = rec.min.x; x < rec.max.x; x++)
        {
            if (barycentric(pos1, pos2, pos3, v2i(x, y), &bary))
            {
                double z = (bary.x * v1.z + bary.y * v2.z + bary.z * v3.z);
                // logger(LOG_DEBUG, "z: %c, zbuf: %f", z, renderer.zbuffer[y][x]);
                if (z < renderer.zbuffer[x + y * GAME_WIDTH])
                    continue;
                renderer.zbuffer[x + y * GAME_WIDTH] = z;

                set_pixel((u32)x, (u32)y, color); // (Color){c, c, c, 255});
            }
        }
    }
}

// Top right, bottom right, top left, bottom left
void set_quad(V2i v1, V2i v2, V2i v3, V2i v4, Color c)
{
    set_triangle(v1, v2, v3, c);
    set_triangle(v1, v3, v4, c);
}

// TODO there is some speed up that could be done here. SIMD
Color get_color_from_texture(Texture *t, V2f uv)
{
    uv.x = fmaxf(0.0f, fminf(1.0f, uv.x));
    uv.y = fmaxf(0.0f, fminf(1.0f, uv.y));

    size_t x = (size_t)(uv.x * (t->width));
    size_t y = (size_t)(uv.y * (t->height));

    size_t idx = (y * t->width + x) * t->stride;

    Color c;
    c.r = t->data[idx + 0];
    c.g = t->data[idx + 1];
    c.b = t->data[idx + 2];
    // TODO add ability to have clear parts from a texture come through
    c.a = t->stride == 4 ? t->data[idx + 3] : 255;
    return c;
}

void clear_background(Color color)
{
    for (s32 y = 0; y < renderer.height; y++)
    {
        for (s32 x = 0; x < renderer.width; x++)
        {
            size_t idx = PIXEL_INDEX(x, y);
            renderer.pixels[idx] = color.rgba;
            renderer.zbuffer[idx] = FLT_MAX;
        }
    }
}

void draw_model(Asset_Model *model, V3f position, Mat3 rotation)
{
    Mat4 view = camera_matrix(renderer.camera);
    for (s32 i = 0; i < arrlen(model->vertices); i += 3)
    {
        Vertex v1 = model->vertices[i];
        Vertex v2 = model->vertices[i + 1];
        Vertex v3 = model->vertices[i + 2];

        V3f p1 = v3f_mul_mat3(v1.position, rotation);
        V3f p2 = v3f_mul_mat3(v2.position, rotation);
        V3f p3 = v3f_mul_mat3(v3.position, rotation);

        V3f n1 = v3f_mul_mat3(v1.normal, rotation);
        V3f n2 = v3f_mul_mat3(v2.normal, rotation);
        V3f n3 = v3f_mul_mat3(v3.normal, rotation);

        p1.z = -p1.z;
        p2.z = -p2.z;
        p3.z = -p3.z;
        p1 = v3f_add(p1, position);
        p2 = v3f_add(p2, position);
        p3 = v3f_add(p3, position);

        p1 = v3f_translate_by_mat4(p1, view);
        p2 = v3f_translate_by_mat4(p2, view);
        p3 = v3f_translate_by_mat4(p3, view);

        if (p1.z >= NEAR && p2.z >= NEAR && p3.z >= NEAR)
        {
            Color t1;
            Color t2;
            Color t3;
            t1 = COLOR_WHITE;
            t2 = COLOR_WHITE;
            t3 = COLOR_WHITE;

			V3f positions[3] = {p1, p2, p3};
			V3f normals[3] = {n1, n2, n3};
            Color colors[3] = {t1, t2, t3};
            V3f uvs[3] = {v1.uv, v2.uv, v3.uv};

            if (model->mtl != NULL)
                renderer_push_triangle_w_normals(
						positions,
						normals,
                        colors,
                        uvs,
                        model->mtl->diffuse_texture,
						model->mtl,
                        0);
            else
                renderer_push_triangle(
                        p1,
                        p2,
                        p3,
                        colors,
                        uvs,
                        NULL,
                        0);
        }
    }
}

void draw_model_with_light(Asset_Model *model, V3f position, Mat3 rotation, Light light)
{
    // Mat4 pers = perspective(NEAR, FAR, ASPECT_RATIO, FOV);
    Mat4 view = camera_matrix(renderer.camera);
    for (s32 i = 0; i < arrlen(model->vertices); i += 3)
    {
        Vertex v1 = model->vertices[i];
        Vertex v2 = model->vertices[i + 1];
        Vertex v3 = model->vertices[i + 2];

        V3f p1 = v3f_mul_mat3(v1.position, rotation);
        V3f p2 = v3f_mul_mat3(v2.position, rotation);
        V3f p3 = v3f_mul_mat3(v3.position, rotation);

        V3f n1 = v3f_mul_mat3(v1.normal, rotation);
        V3f n2 = v3f_mul_mat3(v2.normal, rotation);
        V3f n3 = v3f_mul_mat3(v3.normal, rotation);

        p1.z = -p1.z;
        p2.z = -p2.z;
        p3.z = -p3.z;
        p1 = v3f_add(p1, position);
        p2 = v3f_add(p2, position);
        p3 = v3f_add(p3, position);

        p1 = v3f_translate_by_mat4(p1, view);
        p2 = v3f_translate_by_mat4(p2, view);
        p3 = v3f_translate_by_mat4(p3, view);

        if (p1.z >= NEAR && p2.z >= NEAR && p3.z >= NEAR)
        {
            Color t1;
            Color t2;
            Color t3;
            t1 = COLOR_WHITE;
            t2 = COLOR_WHITE;
            t3 = COLOR_WHITE;

            Color c1 = simple_reflection(model->mtl, light.position, p1, n1, light.color, t1);
            Color c2 = simple_reflection(model->mtl, light.position, p2, n2, light.color, t2);
            Color c3 = simple_reflection(model->mtl, light.position, p3, n3, light.color, t3);

            Color colors[3] = {c1, c2, c3};
            V3f uvs[3] = {v1.uv, v2.uv, v3.uv};
            renderer_push_triangle(
                p1,
                p2,
                p3,
                colors,
                uvs,
                model->mtl->diffuse_texture,
                0);
        }
    }
}

Color simple_reflection(SimpleMtl *mtl, V3f light_pos, V3f v, V3f n, V3f light_color, Color object_color)
{
    if (mtl == NULL)
        return object_color;
    V3f norm = v3f_normalize(n);
    V3f light_dir = v3f_normalize(v3f_sub(v, light_pos));

    f32 diff = fmaxf(v3f_dot(norm, light_dir), 0.0f);

    V3f obj = {
        object_color.r / 255.0,
        object_color.g / 255.0,
        object_color.b / 255.0,
    };
    V3f diffuse = v3f_scale(light_color, diff);
    V3f result = v3f_mul(v3f_add(diffuse, mtl->ambient), obj);

    Color res = (Color){
        .r = (u8)(fminf(result.x, 1.0f) * 255),
        .g = (u8)(fminf(result.y, 1.0f) * 255),
        .b = (u8)(fminf(result.z, 1.0f) * 255),
        .a = 255,
    };
    return res;
}

void draw_texture(Texture *tex, Recs32 rec)
{
    f32 x0 = rec.x;
    f32 y0 = rec.y;
    f32 x1 = rec.x + rec.w;
    f32 y1 = rec.y + rec.h;

    // Tri 1: TL, BR, BL
    V3f uvs1[3] = {
        {1.0f, 1.0f, 1.0f}, // BR
        {1.0f, 0.0f, 1.0f}, // TR
        {0.0f, 0.0f, 1.0f}, // TL
    };
    // Tri 2: TL, TR, BR
    V3f uvs2[3] = {
        {0.0f, 1.0f, 1.0f}, // BL
        {1.0f, 1.0f, 1.0f}, // BR
        {0.0f, 0.0f, 1.0f}, // TL
    };

    Color colors[3] = {};

    renderer_push_triangle(
        v3f(x1, y1, 1), // BR
        v3f(x1, y0, 1), // TR
        v3f(x0, y0, 1), // TL
        colors, uvs1, tex, TRIANGLE_TWO_D);

    renderer_push_triangle(
        v3f(x0, y1, 1), // BL
        v3f(x1, y1, 1), // BR
        v3f(x0, y0, 1), // TL
        colors, uvs2, tex, TRIANGLE_TWO_D);
}

void draw_texture_w_uvs(Texture *tex, Recs32 rec, V3f uvs[4], Color colors[4])
{
    f32 x0 = rec.x;
    f32 y0 = rec.y;
    f32 x1 = rec.x + rec.w;
    f32 y1 = rec.y + rec.h;

    // Tri 1: TL, BR, BL
    V3f uvs1[3] = {
        uvs[2],
        uvs[1],
        uvs[0]};

    // Tri 2: TL, TR, BR
    V3f uvs2[3] = {
        uvs[3],
        uvs[2],
        uvs[0]};

    Color c1[3] = {
        colors[2],
        colors[1],
        colors[0],
    };

    Color c2[3] = {
        colors[3],
        colors[2],
        colors[0],
    };

    renderer_push_triangle(
        v3f(x1, y1, 0.1), // BR
        v3f(x1, y0, 0.1), // TR
        v3f(x0, y0, 0.1), // TL
        c1, uvs1, tex, TRIANGLE_TWO_D);

    renderer_push_triangle(
        v3f(x0, y1, 0.1), // BL
        v3f(x1, y1, 0.1), // BR
        v3f(x0, y0, 0.1), // TL
        c2, uvs2, tex, TRIANGLE_TWO_D);
}

void draw_recs32(Recs32 rec, f32 z, Color color)
{
    f32 x0 = rec.x;
    f32 y0 = rec.y;
    f32 x1 = rec.x + rec.w;
    f32 y1 = rec.y + rec.h;

    V3f uvs[3] = {};
    Color colors[3] = {color, color, color};

    renderer_push_triangle(
        v3f(x1, y1, z), // BR
        v3f(x1, y0, z), // TR
        v3f(x0, y0, z), // TL
        colors, uvs, NULL, TRIANGLE_TWO_D);

    renderer_push_triangle(
        v3f(x0, y1, z), // BL
        v3f(x1, y1, z), // BR
        v3f(x0, y0, z), // TL
        colors, uvs, NULL, TRIANGLE_TWO_D);
}

// TODO AI GENERATED. REVISIT FOR FIXES

#define GLYPH_W 32 
#define GLYPH_H 32 

void draw_text(Font *f, const char *str, V2i pos, f32 size, Color color)
{
    s32 atlas_w = f->texture->width;
    s32 atlas_h = f->texture->height;
    s32 sprites_per_row = atlas_w / GLYPH_W;

    char c = str[0];
    s32 i = 0;
    while (c != '\0')
    {
        s32 tex_id = (u8)c;
        s32 col = tex_id % sprites_per_row;
        s32 row = tex_id / sprites_per_row;

        f32 du = 0.5f / (f32)atlas_w;
        f32 dv = 0.5f / (f32)atlas_h;

        f32 u_min = ((f32)(col * GLYPH_W) + 0.5f) / (f32)atlas_w;
        f32 v_min = ((f32)(row * GLYPH_H) + 0.5f) / (f32)atlas_h;
        f32 u_max = ((f32)(col * GLYPH_W + GLYPH_W) - 0.5f) / (f32)atlas_w;
        f32 v_max = ((f32)(row * GLYPH_H + GLYPH_H) - 0.5f) / (f32)atlas_h;

        V3f uvs[4] = {
            v3f(u_min, v_min, 0), /* top-left     */
            v3f(u_max, v_min, 0), /* top-right    */
            v3f(u_max, v_max, 0), /* bottom-right */
            v3f(u_min, v_max, 0), /* bottom-left  */
        };
        Color colors[4] = {color, color, color, color};
        Recs32 rec = (Recs32){.x = pos.x + (i * (s32)size), .y = pos.y, .w = (s32)size, .h = (s32)size};
        draw_texture_w_uvs(
            f->texture,
            rec,
            uvs,
            colors);

        i++;
        c = str[i];
    }
}

void draw_string8(Font *f, String8 str, V2i pos, f32 size, Color color)
{
    s32 atlas_w = f->texture->width;
    s32 atlas_h = f->texture->height;
    s32 sprites_per_row = atlas_w / GLYPH_W;

    for (u32 i = 0; i < str.len; i++) {
        char c = str.data[i];
        s32 tex_id = (u8)c;
        s32 col = tex_id % sprites_per_row;
        s32 row = tex_id / sprites_per_row;

        f32 du = 0.5f / (f32)atlas_w;
        f32 dv = 0.5f / (f32)atlas_h;

        f32 u_min = ((f32)(col * GLYPH_W) + 0.5f) / (f32)atlas_w;
        f32 v_min = ((f32)(row * GLYPH_H) + 0.5f) / (f32)atlas_h;
        f32 u_max = ((f32)(col * GLYPH_W + GLYPH_W) - 0.5f) / (f32)atlas_w;
        f32 v_max = ((f32)(row * GLYPH_H + GLYPH_H) - 0.5f) / (f32)atlas_h;

        V3f uvs[4] = {
            v3f(u_min, v_min, 0), /* top-left     */
            v3f(u_max, v_min, 0), /* top-right    */
            v3f(u_max, v_max, 0), /* bottom-right */
            v3f(u_min, v_max, 0), /* bottom-left  */
        };
        Color colors[4] = {color, color, color, color};
        Recs32 rec = (Recs32){.x = pos.x + (i * (s32)size), .y = pos.y, .w = (s32)size, .h = (s32)size};
        draw_texture_w_uvs(
            f->texture,
            rec,
            uvs,
            colors);
    }
}

void draw_rectangle3d(V3f bl, V3f br, V3f tl, V3f tr, Color color, u32 flags)
{
    Mat4 view = camera_matrix(renderer.camera);

    V3f uvs[3] = {};
    Color colors[3] = {color, color, color};
    V3f p1 = v3f_translate_by_mat4(bl, view);
    V3f p2 = v3f_translate_by_mat4(br, view);
    V3f p3 = v3f_translate_by_mat4(tl, view);
    V3f p4 = v3f_translate_by_mat4(tr, view);

    if (p1.z <= NEAR || p2.z <= NEAR || p3.z <= NEAR || p4.z <= NEAR)
        return;

    // Tri 1: was BR, TR, TL (clockwise = back face) → flip to TL, TR, BR
    renderer_push_triangle(
            p3, // TL
            p4, // TR
            p2, // BR
            colors, uvs, NULL, TRIANGLE_NO_CULLING | flags);

    // Tri 2: was BL, BR, TL (clockwise = back face) → flip to TL, BR, BL
    renderer_push_triangle(
            p3, // TL
            p2, // BR
            p1, // BL
            colors, uvs, NULL, TRIANGLE_NO_CULLING | flags);
}

void draw_texture3d(Texture *tex, V3f bl, V3f br, V3f tl, V3f tr, Color color, u32 flags)
{
    Mat4 view = camera_matrix(renderer.camera);

    V3f uvs[3] = {};
    Color colors[3] = {color, color, color};
    V3f p1 = v3f_translate_by_mat4(bl, view);
    V3f p2 = v3f_translate_by_mat4(br, view);
    V3f p3 = v3f_translate_by_mat4(tl, view);
    V3f p4 = v3f_translate_by_mat4(tr, view);

    // Tri 1: TL, BR, BL
    V3f uvs1[3] = {
        {0.0f, 0.0f, 1.0f}, // TL
        {1.0f, 0.0f, 1.0f}, // TR
        {1.0f, 1.0f, 1.0f}, // BR
    };
    // Tri 2: TL, TR, BR
    V3f uvs2[3] = {
        {0.0f, 0.0f, 1.0f}, // TL
        {1.0f, 1.0f, 1.0f}, // BR
        {0.0f, 1.0f, 1.0f}, // BL
    };

    if (p1.z <= NEAR || p2.z <= NEAR || p3.z <= NEAR || p4.z <= NEAR)
        return;

    // Tri 1: was BR, TR, TL (clockwise = back face) → flip to TL, TR, BR
    renderer_push_triangle(
            p3, // TL
            p4, // TR
            p2, // BR
            colors, uvs1, tex, TRIANGLE_NO_CULLING | flags);

    // Tri 2: was BL, BR, TL (clockwise = back face) → flip to TL, BR, BL
    renderer_push_triangle(
            p3, // TL
            p2, // BR
            p1, // BL
            colors, uvs2, tex, TRIANGLE_NO_CULLING | flags);
}

void draw_triangle3d(V3f v1, V3f v2, V3f v3, Color color, u32 flags)
{
    Mat4 view = camera_matrix(renderer.camera);
    Color colors[3] = {color, color, color};
    V3f p1 = v3f_translate_by_mat4(v1, view);
    V3f p2 = v3f_translate_by_mat4(v2, view);
    V3f p3 = v3f_translate_by_mat4(v3, view);
    V3f uvs[3] = {0};

    if (p1.z <= NEAR || p2.z <= NEAR || p3.z <= NEAR)
        return;
    renderer_push_triangle(
            p1, p2, p3,
            colors, uvs, NULL, TRIANGLE_NO_CULLING | flags);
}

